[package]
name = "rddit-2"
version = "0.1.0"
authors = ["johannes"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"
rddit_framework_2 = {git = "https://github.com/JohannesThoren/rddit_framework_2.0"}